[package]
name = "picket-agent"
version = "0.6.2"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
clap = { version = "4", features = ["derive"] }
ureq = { version = "2", features = ["tls"] }
toml = "0.8"
libc = "0.2"
regex = "1"
glob = "0.3"
picket-common = { path = "../picket-common" }

[target.'cfg(target_os = "linux")'.dependencies]
inotify = "0.10"
